dist: xenial
addons:
  apt:
    sources:
      - docker-xenial

env:
  global:
  # The following variables are setup via gitlab project group:
  # - DOCKER_HUB_TOKEN
  # - DOCKER_SLUG
  # - DOCKER_USERNAME
  # - DOCKER_PASSWORD
  # - CUSTOM_REGISTRY_URL
  # - CUSTOM_REGISTRY_USER
  # - CUSTOM_REGISTRY_PW
  - DOCKER_SLUG: "8ear"
  matrix:
  - VERSION=0.1-alpine
  - VERSION=1.0-debian

#
# Install dependencies
#
before_install:
- sudo .ci/01_before_install.sh

#
# Build and tag our image
#
script:
- make build v=${VERSION} prod=false      # Set prod=true, if you want to build NO '-dev' tag
- make tags REPO=$DOCKER_SLUG prod=false  # Set prod=true, if you want tags NO '-dev' tag

#
# Push all Images found with the current Docker container name to the Docker registries
#
deploy:
  provider: script
  script: 
  - bash .ci/04_push_2_registry.sh REPO=$DOCKER_SLUG USER=$DOCKER_USERNAME PW=$DOCKER_PASSWORD
  on:
    branch: master

#
# Trigger hub.docker.com automatic_build queue to update Readme
#
after_success:
# [OPTIONAL] Notify Docker hub about a new Readme and update the content 
#- if [[ "$TRAVIS_BRANCH" == "master" ]]; then make notify-hub-docker-com TOKEN=$DOCKER_HUB_TOKEN;  fi; 

notifications:
  # don't notify me when things fail
  email: false