dist: xenial
addons:
  apt:
    sources:
      - docker-xenial

env:
  global:
  # The following variables are setup via gitlab project group:
  # - DOCKER_HUB_TOKEN
  # - DOCKER_SLUG
  # - DOCKER_USERNAME
  # - DOCKER_PASSWORD
  # - CUSTOM_REGISTRY_URL
  # - CUSTOM_REGISTRY_USER
  # - CUSTOM_REGISTRY_PW
  - DOCKER_SLUG: "8ear"
  matrix:
  - VERSION=0.1-alpine
  - VERSION=1.0-debian

#
# Install dependencies
#
before_install:
- sudo .ci/01_before_install.sh

#
# Build and tag our image
#
script:
- make -C .ci build v=${VERSION} prod=false      # Set prod=true, if you want to build NO '-dev' tag  # build an not2push/CONTAINERNAME image
- make -C .ci tags REPO=$DOCKER_SLUG prod=false  # Set prod=true, if you want tags NO '-dev' tag # tagged custom-URL/CONTAINERNAME
  #- make -C .ci tags REPO=$CUSTOM_REGISTRY_URL

#
# Push all Images found with the current Docker container name to the Docker registries
#
# deploy:
#   provider: script
#   script: 
#     - make -C .ci push REPO=$CUSTOM_REGISTRY_URL USER=$CUSTOM_REGISTRY_USER PW=$CUSTOM_REGISTRY_PW
#     - make -C .ci push REPO=$DOCKER_SLUG USER=$DOCKER_USERNAME PW=$DOCKER_PASSWORD
#     - make -C .ci notify-hub-docker-com REPO=$DOCKER_SLUG TOKEN=$DOCKER_HUB_TOKEN
#   on:
#     branch: master

#
# Trigger hub.docker.com automatic_build queue to update Readme
#
after_success:
# [OPTIONAL] Notify Docker hub about a new Readme and update the content 
#- if [[ "$TRAVIS_BRANCH" == "master" ]]; then make -C .ci notify-hub-docker-com TOKEN=$DOCKER_HUB_TOKEN;  fi; 

notifications:
  # don't notify me when things fail
  email: false